### ISSUE TITLE
Force close

### ISSUE THREAD

**Issue by Eva850** [Xlythe/Calculator#51]
When I swipe to left to open functions panel then press back button, app force closes. Here is a logcat: 

java.lang.RuntimeException: Cannot animate in collapsed state
    at com.xlythe.calculator.material.view.CalculatorPadView$DisplayAnimator.onUpdate(CalculatorPadView.java:540)
    at com.xlythe.calculator.material.view.CalculatorPadView$DisplayAnimator$1.onAnimationUpdate(CalculatorPadView.java:523)
    at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
    at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:642)
    at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:589)
    at android.animation.ValueAnimator.start(ValueAnimator.java:1106)
    at android.animation.ValueAnimator.start(ValueAnimator.java:1117)
    at com.xlythe.calculator.material.view.CalculatorPadView.collapse(CalculatorPadView.java:414)
    at com.xlythe.calculator.material.view.CalculatorPadView.collapse(CalculatorPadView.java:396)
    at com.xlythe.calculator.material.BasicCalculator.onBackPressed(BasicCalculator.java:425)
    at com.xlythe.calculator.material.GraphingCalculator.onBackPressed(GraphingCalculator.java:306)
    at android.app.Activity.onKeyUp(Activity.java:2488)
    at android.view.KeyEvent.dispatch(KeyEvent.java:2685)
    at android.app.Activity.dispatchKeyEvent(Activity.java:2741)
    at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:547)
    at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:57)
    at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:315)
    at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2317)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4131)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4093)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3791)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3673)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3848)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3673)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3791)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3673)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3848)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3673)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3791)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3673)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3848)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5926)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5900)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5861)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6029)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
    at android.os.MessageQueue.nativePollOnce(Native Method)
    at android.os.MessageQueue.next(MessageQueue.java:331)
    at android.os.Looper.loop(Looper.java:218)
    at android.app.ActivityThread.main(ActivityThread.java:5526)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by Xlythe** [comment]
That's... really weird. Do you mind giving me a bit more info?

1) When you press 'back', does the calculator immediately crash? Or does it animate closed and then crash?
2) How do you open the panel? Do you fling it? What about dragging it > 50% and then letting go with 0 velocity?

**Comment by Xlythe** [comment]
Also, what version of android are you on? And what kind of phone?

**Comment by Eva850** [comment]
App version 6.0.7, Android 6.0.1 Xperia Z5

**Comment by Eva850** [comment]
There is a video which explains when it exactly force close. https://drive.google.com/file/d/0B6g6Av7dwyPFUGFXaUJCU2toLTA/view?usp=drivesdk

**Comment by Xlythe** [comment]
Awesome! I've reproduced it :)
